language: node_js
node_js:
  - "8.11.3"

branches:
  only:
  - master

install:
  - yarn install

script:
  - npm run build
  - npm run deploy

notifications:
  email:
    on_failure: change
    on_success: change

